[window]
opacity = 0.7

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular"}
bold = { family = "Hack Nerd Font Mono", style = "Bold"}
italic = { family = "Hack Nerd Font Mono", style = "Italic"}
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic"}
size = 15.0

[colors.primary]
background = "#000000"

[colors.normal]
black = "#000000"
red = "#CC0403"
green = "#19CB00"
yellow = "#CECB00"
blue = "#0D73CC"
magenta = "#CB1ED1"
cyan = "#0DCDCD"
white = "#DDDDDD"

[colors.bright]
black = "#767676"
red = "#F2202F"
green = "#23FD00"
yellow = "#FFFD00"
blue = "#1A8FFF"
magenta = "#FD28FF"
cyan = "#14FFFF"
white = "#FFFFFF"

