[window]
opacity = 0.7
dynamic_padding = true

[font]
normal = { family = "monospace", style = "Regular"}
bold = { family = "monospace", style = "Bold"}
italic = { family = "monospace", style = "Italic"}
bold_italic = { family = "monospace", style = "Bold Italic"}
size = 14.0

[general]
import = [
    "~/.cache/wal/colors-alacritty.toml"
]

[colors.primary]
background = "#000000"
