[window]
opacity = 0.7
dynamic_padding = true

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular"}
bold = { family = "Hack Nerd Font Mono", style = "Bold"}
italic = { family = "Hack Nerd Font Mono", style = "Italic"}
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic"}
size = 14.0

[general]
import = [
	"~/.config/alacritty/tokyodark.toml"
]

[colors.primary]
background = "#000000"
#
# [colors.normal]
# black = "#000000"
# red = "#FF263F"
# green = "#A9E15C"
# yellow = "#FDD33F"
# blue = "#0093FD"
# magenta = "#9B5EE9"
# cyan = "#66FFF3"
# white = "#FEFEFE"
#
# [colors.bright]
# black = "#434343"
# red = "#FF010F"
# green = "#8BE20A"
# yellow = "#FEB800"
# blue = "#018CF5"
# magenta = "#6D45A8"
# cyan = "#02D9EB"
# white = "#FEFEFE"
